"""
GUI package that handles the interaction logic.
Modules starting with `ui_` are automatically generated by `PyQt Ui Designer`.
Classes in other modules, such as `mainwindow.MainWindow`, inherit from `ui_mainwindow.Ui_Window`
, and so on.
"""

from ui.mainwindow import MainWindow
from ui.rename import RenameDialog
from ui.move import MoveDialog
