# Form implementation generated from reading ui file 'rename_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog.resize(628, 537)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(540, 470, 81, 61))
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Chinese, QtCore.QLocale.Country.China))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 13, 521, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_module = QtWidgets.QHBoxLayout()
        self.horizontalLayout_module.setObjectName("horizontalLayout_module")
        self.label_module = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_module.setObjectName("label_module")
        self.horizontalLayout_module.addWidget(self.label_module)
        self.lineEdit_module = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_module.setReadOnly(True)
        self.lineEdit_module.setObjectName("lineEdit_module")
        self.horizontalLayout_module.addWidget(self.lineEdit_module)
        self.verticalLayout.addLayout(self.horizontalLayout_module)
        self.horizontalLayout_new_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_new_name.setObjectName("horizontalLayout_new_name")
        self.label_new_name = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_new_name.setObjectName("label_new_name")
        self.horizontalLayout_new_name.addWidget(self.label_new_name)
        self.lineEdit_new_name = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_new_name.setReadOnly(False)
        self.lineEdit_new_name.setObjectName("lineEdit_new_name")
        self.horizontalLayout_new_name.addWidget(self.lineEdit_new_name)
        self.verticalLayout.addLayout(self.horizontalLayout_new_name)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.lineEdit_new_name.editingFinished.connect(Dialog.slot_set_new_name) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Rename"))
        self.label_module.setText(_translate("Dialog", "Module"))
        self.label_new_name.setText(_translate("Dialog", "New Name"))
        self.label.setText(_translate("Dialog", "Preview"))
